import type { UpdateItem } from '@/app/ng/news/NewsClient';

export const internationalNewsItems: UpdateItem[] = [
  {
    id: 'global-health-uhc',
    type: 'news',
    title: 'Global health equity: Universal Health Coverage (UHC)',
    summary: 'A global overview of UHC and the path to equitable access to quality health services without financial hardship.',
    date: '2025-01-10T00:00:00.000Z',
    badge: 'Global Health',
    href: 'https://www.who.int/health-topics/universal-health-coverage',
    imageId: 'news-good-health',
    imageUrl: null,
    sourceLabel: 'World Health Organization',
  },
  {
    id: 'human-rights-un',
    type: 'news',
    title: 'Human rights: UN resources and global updates',
    summary: 'Key guidance and updates on protecting rights, strengthening civic space, and advancing equality worldwide.',
    date: '2025-01-12T00:00:00.000Z',
    badge: 'Human Rights',
    href: 'https://www.ohchr.org/en/press-releases',
    imageId: 'news-peace-justice',
    imageUrl: null,
    sourceLabel: 'UN Human Rights (OHCHR)',
  },
  {
    id: 'gender-equality-un-women',
    type: 'news',
    title: 'Gender equality: global briefs and announcements',
    summary: 'Updates and evidence on closing gender gaps, preventing violence, and strengthening inclusive systems.',
    date: '2025-01-15T00:00:00.000Z',
    badge: 'Gender Equality',
    href: 'https://www.unwomen.org/en/news',
    imageId: 'news-gender-equality',
    imageUrl: null,
    sourceLabel: 'UN Women',
  },
  {
    id: 'climate-resilience-undp',
    type: 'news',
    title: 'Climate change and resilience: global solutions',
    summary: 'International work on climate resilience, disaster risk reduction, and community-led adaptation.',
    date: '2025-01-18T00:00:00.000Z',
    badge: 'Climate & Resilience',
    href: 'https://www.undp.org/climate-change',
    imageId: 'news-climate-report',
    imageUrl: null,
    sourceLabel: 'UNDP',
  },
  {
    id: 'disability-inclusion-who',
    type: 'news',
    title: 'Disability inclusion in health systems',
    summary: 'Global guidance and resources on making health services accessible, inclusive, and disability-friendly.',
    date: '2025-01-20T00:00:00.000Z',
    badge: 'Disability Inclusion',
    href: 'https://www.who.int/health-topics/disability',
    imageId: 'news-reduced-inequalities',
    imageUrl: null,
    sourceLabel: 'World Health Organization',
  },
  {
    id: 'mental-health-who',
    type: 'news',
    title: 'Mental health: global news and initiatives',
    summary: 'International updates on mental wellbeing, community support, and better access to care.',
    date: '2025-01-22T00:00:00.000Z',
    badge: 'Mental Health',
    href: 'https://www.who.int/health-topics/mental-health',
    imageId: 'news-health-innovation',
    imageUrl: null,
    sourceLabel: 'World Health Organization',
  },
  {
    id: 'education-unesco',
    type: 'news',
    title: 'Education access: global news and reports',
    summary: 'International education updates focused on inclusion, literacy, and equitable access for learners.',
    date: '2025-01-25T00:00:00.000Z',
    badge: 'Education',
    href: 'https://www.unesco.org/en/articles',
    imageId: 'news-quality-education',
    imageUrl: null,
    sourceLabel: 'UNESCO',
  },
  {
    id: 'economic-inclusion-world-bank',
    type: 'news',
    title: 'Economic empowerment and inclusion: global insights',
    summary: 'Global perspectives on jobs, social protection, and inclusive economic growth.',
    date: '2025-01-28T00:00:00.000Z',
    badge: 'Economic Empowerment',
    href: 'https://www.worldbank.org/en/topic/jobsanddevelopment',
    imageId: 'news-decent-work',
    imageUrl: null,
    sourceLabel: 'World Bank',
  },
];

